name=input("Enter the name of student:")
age=int(input("enter age of student:"))
a=int(input("enter the marks of mathematics:"))
b=int(input("enter the marks of science:"))
c=int(input("enter the marks of tamil:"))
d=int(input("enter the marks of english:"))
e=int(input("enter the marks of saivanery:"))
f=int(input("enter the marks of history:"))
total=(a+b+c+d+e+f)
average=(total/6)
print("**************************")
print("name of the student:",name)
print("age of the student :",age)
print("total marks :",total)
print("average marks:",average)
print("**************************")